// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VID.Data;

#nullable disable

namespace VID.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250306112757_VisualMigratesFinal")]
    partial class VisualMigratesFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VID.Models.Applicant", b =>
                {
                    b.Property<int>("ApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("APPLICANT_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApplicantId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("ApplicantId"), 2L, null, null, null, null, null);

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("PERSON_ID");

                    b.Property<string>("UserPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("USER_PHONE_NUMBER");

                    b.Property<int>("statud_id")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ID");

                    b.HasKey("ApplicantId");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("VID.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("APPLICATION_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApplicationId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("ApplicationId"), 2L, null, null, null, null, null);

                    b.Property<int>("ApplicantId")
                        .HasColumnType("integer")
                        .HasColumnName("APPLICANT_ID");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CITIZENSHIP");

                    b.Property<string>("CountryOfBirth")
                        .HasColumnType("text")
                        .HasColumnName("COUNTRYOFBIRTH");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("DOCUMENT_ID");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NATIONALITY");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("STATUS");

                    b.HasKey("ApplicationId");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("VID.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DOCUMENT_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("DocumentId"), 2L, null, null, null, null, null);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("APPLICATION_ID");

                    b.Property<byte[]>("BirthCertificate")
                        .HasColumnType("bytea")
                        .HasColumnName("DOCUMENT_BIRTHCERTIFICATE");

                    b.Property<string>("DocumentCode")
                        .HasColumnType("text")
                        .HasColumnName("DOCUMENT_CODE");

                    b.Property<byte[]>("IdCopy")
                        .HasColumnType("bytea")
                        .HasColumnName("DOCUMENT_IDENTITY_NUMBER_COPY");

                    b.Property<int?>("IdentityId")
                        .HasColumnType("integer")
                        .HasColumnName("IDENTITY_ID");

                    b.HasKey("DocumentId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("VID.Models.NextOfKin", b =>
                {
                    b.Property<int>("NextOfKinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NEXT_OF_KIN_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NextOfKinId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("NextOfKinId"), 2L, null, null, null, null, null);

                    b.Property<string>("NextOfKinPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("NEXT_OF_KIN_PHONENUMBER");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("PERSON_ID");

                    b.Property<string>("Relationship")
                        .HasColumnType("text")
                        .HasColumnName("RELATIONSHIP");

                    b.HasKey("NextOfKinId");

                    b.ToTable("NextOfKin");
                });

            modelBuilder.Entity("VID.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PERSON_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("PersonId"), 2L, null, null, null, null, null);

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("DATEOFBIRTH");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("Firstname")
                        .HasColumnType("text")
                        .HasColumnName("FIRSTNAME");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("GENDER");

                    b.Property<string>("Surname")
                        .HasColumnType("text")
                        .HasColumnName("SURNAME");

                    b.Property<string>("UserPassword")
                        .HasColumnType("text")
                        .HasColumnName("USER_PASSWORD");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("VID.Models.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusID"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("StatusID"), 2L, null, null, null, null, null);

                    b.Property<string>("StatusName")
                        .HasColumnType("text")
                        .HasColumnName("STATUS_NAME");

                    b.HasKey("StatusID");

                    b.ToTable("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
